# Generated by Django 5.0.7 on 2024-07-28 13:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='state',
            field=models.CharField(choices=[('D', 'Draft'), ('I', 'In Progress'), ('C', 'Completed'), ('X', 'Cancelled')], default='D', max_length=1),
        ),
    ]
