# Generated by Django 5.0.7 on 2024-07-29 01:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0002_changed_state_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='creation_date',
            field=models.DateField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='project',
            name='due_date',
            field=models.DateField(),
        ),
    ]
