# Generated by Django 5.0.7 on 2024-07-29 21:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0003_alter_project_creation_date_alter_project_due_date'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Profile',
        ),
    ]
